### ISSUE TITLE
Pynetstring doesn't handle negative length values

### ISSUE THREAD

**Issue by Snawoot** [rj79/pynetstring#5]
```
>>> pynetstring.decode(b'-20:,')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/omnipotent/venvs/pynetstring-dev/lib64/python3.7/site-packages/pynetstring.py", line 66, in decode
    return decoder.feed(data)
  File "/home/omnipotent/venvs/pynetstring-dev/lib64/python3.7/site-packages/pynetstring.py", line 53, in feed
    if self._buffer[self._length] != ord(b','):
IndexError: bytearray index out of range
```

**Comment by rj79** [comment]
Fixed in commit 6b98a0046807d18269e9a13bcee168cfae3fcdf5.
